In [ ]:
pip install nbconvert


# HW2: Problem 2: Working out Backpropagation

Read Chapter 2 of Michael Nielsen's article/book from top to bottom:

* [http://neuralnetworksanddeeplearning.com/chap2.html](http://neuralnetworksanddeeplearning.com/chap2.html)

He outlines a few exersizes in that article which you must complete. Do the following a, b, c:

a. He invites you to write out a proof of equation BP3

b. He invites you to write out a proof of equation BP4

c. He proposes that you code a fully matrix-based approach to backpropagation over a mini-batch. Implement this with explanation where you change the notation so that instead of having a bias term, you assume that the input variables are augmented with a "column" of "1"s, and that the weights $w_0$.

Your submission should be a single jupyter notebook. Use markdown cells with latex for equations of a jupyter notebook for each proof for "a." and "b.". Make sure you include text that explains your steps. Next for "c" this is an implementation problem. You need to understand and modify the code the Michael Nielsen provided so that instead it is using a matrixed based approach. Again don't keep the biases separate. After reading data in (use the iris data set), create a new column corresponding to $x_0=1$, and as mentioned above and discussed in class (see notes) is that the bias term can then be considered a weight $w_0$. Again use markdown cells around your code and comments to explain your work. Test the code on the iris data set with 4 node input (5 with a constant 1), three hidden nodes, and three output nodes, one for each species/class.

## a. Proof of Michael Nielsons equation BP3


Deriving BP3 is very similar to how BP1 was derived, except we also do partial derivative on Z with respect to bias b since Z also depends on b


$ \frac{\partial C}
{\partial b_j^L}= \Sigma_k \frac{\partial C}
{\partial a_k^L}*\frac{\partial a_k^L}
{\partial z_j^L}*\frac{\partial z_j^L}
{\partial b_j^L} $

$z_j^L = \Sigma_k w_{jk}^L * a_k^{L-1} + b_j^L $

$\frac{\partial z_j^L}{\partial b_j^L} = 1$

Thus:

$ \frac{\partial C}
{\partial b_j^L}= \Sigma_k \frac{\partial C}
{\partial a_k^L}*\frac{\partial a_k^L}
{\partial z_j^L} = \delta_j^L $



## b. Proof of Michael Nielsons equation BP4

To solve this lets seperate $\frac{\partial C}
{\partial \omega_{jk}^L}$ using chain rule:

$\frac{\partial C}
{\partial \omega_{jk}^L} = \Sigma_k \frac{\partial C}
{\partial a_k^L}*\frac{\partial a_k^L}
{\partial z_j^L}*\frac{\partial z_j^L}
{\partial w_{jk}^L} $

$z_j^L = \Sigma_k w_{jk}^L * a_k^{L-1} + b_j^L $

$\frac{\partial z_j^L}{\partial w_{jk}^L} = a_k^{L-1}$

Remember that:

$\delta_j^L = \frac{\partial C}
{\partial z_j^L}= \Sigma_k \frac{\partial C}
{\partial a_k^L}*\frac{\partial a_k^L}
{\partial z_j^L}$

Thus:

$\frac{\partial C}
{\partial \omega_{jk}^L} = \delta_j^L * a_k^{L-1} $

## c. Using both markdown cells and code cells implement that you code a fully matrix-based approach to backpropagation over a mini-batch. Implement this with explanation where you change the notation so that instead of having a bias term, you assume that the input variables are augmented with a "column" of "1"s, and that the weights $w_0$.

First we extract the Iris.csv file

In [213]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

table = pd.read_csv('/content/drive/My Drive/Iris.csv')
table.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

From the csv file, we extract all the inputs and output species to put them into separate columns

In [214]:
Sepal_L = pd.Series(table['SepalLengthCm']).array
Sepal_W = pd.Series(table['SepalWidthCm']).array
Petal_L = pd.Series(table['PetalLengthCm']).array
Petal_W = pd.Series(table['PetalWidthCm']).array
Species = pd.Series(table['Species']).array

Now we must format the Output Column of the data since the activation outputs will return numerical values. Thus we will format the output as a 3 x n matrix with states of [0,0,1], [0,1,0] or [1,0,0] since there are only 3 types of classifactions.

We also augment the Input Matrix with a column of 1s as we are going to be merging the Biases and the Weights into one Matrix

In [220]:
Output_Matrix = np.zeros(3)

In [221]:
Input_Matrix = np.matrix([Sepal_L,Sepal_W,Petal_L,Petal_W,np.ones_like(Sepal_L)])

i = 0
for n in Species: #convert Species into numerical values
  if n == 'Iris-setosa': Output_Matrix = np.row_stack ((Output_Matrix,[0,0,1]))
  elif n == 'Iris-versicolor' : Output_Matrix =  np.row_stack ((Output_Matrix,[0,1,0]))
  elif n == 'Iris-virginica': Output_Matrix = np.row_stack ((Output_Matrix,[1,0,0]))
  i += 1
Output_Matrix




array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [223]:
Output_Matrix = np.delete(Output_Matrix,0,0)
Output_Matrix

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [224]:
Output_Matrix.shape

(150, 3)

Now we will modify the backpropagation code using the matrix approach to merge the weights and biases. We will start the Weights and Bias matrix as a randomized 5 x 3 matrix ( 4 Inputs + 1 Bias -> 3 Activation outputs)

The Third Layer will have a Weight-Bias Matrix of 4 x 3 (3 Activation Outputs from Layer 2 + 1 Bias Term -> 3 Activation Outputs for Layer 3)

This would also mean that we would have to Augment the activation matrix of Layer 2 with another row of 1s for the biases

In [250]:
def backprop(x,y):

        # feedforward
        np.random.seed(42)
        W_2 = np.matrix([np.random.rand(5) , np.random.rand(5), np.random.rand(5)]) # w_2: 5x3 since 4 inputs + 1 bias to 3 activations in Layer 2
        z_2 = np.dot(W_2, x) # z = Input-Bias Matrix . Weight Vector
        a_2 = sigmoid(z_2)

        a_2_bias = np.row_stack((a_2, np.ones(150))) #Augmenting the Activation matrix with Bias Input = 1
        W_3 = np.matrix([np.random.rand(4) , np.random.rand(4), np.random.rand(4)]) # w_3: 4x3 since 3 activations + 1 bias to 3 outputs in Layer 3
        z_3 = np.dot(W_3, a_2_bias)
        a_3 = sigmoid(z_3)
        print("FeedForward Successful")
        # backward pass
        delta_3 = np.multiply(cost_derivative(a_3, y),sigmoid_prime(z_3)) #Error matrix for Layer_3 3x150
        delta_2 = np.multiply(np.dot(np.transpose(W_3),delta_3), np.row_stack((sigmoid_prime(z_2), np.zeros(150)))) #Error matrix for Layer_2
        #also have to augment sigmoid_prime data due to biases, since the bias "activation" input = 1 and is a constant, we can augment a row of zeros
        #since the derivative of a constant term is 0
        gradient_3 = np.dot(a_2_bias,np.transpose(delta_3))
        gradient_2 = np.dot(x, np.transpose(delta_2))
        return (gradient_3, gradient_2)



def cost_derivative(output_activations, y):
        """Return the vector of partial derivatives \partial C_x /
        \partial a for the output activations."""

        return (output_activations-np.transpose(y))

def sigmoid(z):
    """The sigmoid function."""
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    """Derivative of the sigmoid function."""
    return np.multiply(sigmoid(z),(1-sigmoid(z)))

We now output the matrices for the Gradients of all Weights and Biases. The Layer 3 Gradients will be a 4 x 3 Matrix while the Layer 2 Gradients will be a 5 x 3 Matrix

In [251]:
dC_dW3, dC_dW2 = backprop(Input_Matrix, Output_Matrix)
print(dC_dW3) # Each Row are Gradients to applied to weights from 1 input, the last row depicts the Gradients for the Biases
print(' ')
print(dC_dW2)

FeedForward Successful
[[11.06126314 11.39413233  9.51993049]
 [10.78372009 11.11685969  9.54484807]
 [11.01268725 11.35066145  9.51814933]
 [11.07329822 11.40543095  9.51953527]]
 
[[0.0264121  1.20948834 0.20617262 0.        ]
 [0.01689007 0.81160664 0.12411253 0.        ]
 [0.0091915  0.3750603  0.08725492 0.        ]
 [0.00184119 0.06759163 0.02111887 0.        ]
 [0.00534198 0.24196935 0.04021646 0.        ]]


To Visualize a little better of what the output is supposed to represent,
Gradient_3 :

\begin{align}
        \frac{\partial C}
{\partial \omega^3}  = \begin{pmatrix}
         \frac{\partial C}
{\partial \omega_{11}^3} &  \frac{\partial C}
{\partial \omega_{21}^3} &  \frac{\partial C}
{\partial \omega_{31}^3}\\
        \frac{\partial C}
{\partial \omega_{12}^3} &  \frac{\partial C}
{\partial \omega_{22}^3} &  \frac{\partial C}
{\partial \omega_{32}^3}\\
        \frac{\partial C}
{\partial \omega_{13}^3} &  \frac{\partial C}
{\partial \omega_{23}^3} &  \frac{\partial C}
{\partial \omega_{33}^3}\\
        \frac{\partial C}
{\partial \beta_1^3} &  \frac{\partial C}
{\partial \beta_2^3} &  \frac{\partial C}
{\partial \beta_3^3}\\
        \end{pmatrix}.
    \end{align}

 And Gradient 2:   

\begin{align}
        \frac{\partial C}
{\partial \omega^2}  = \begin{pmatrix}
         \frac{\partial C}
{\partial \omega_{11}^2} &  \frac{\partial C}
{\partial \omega_{21}^2} &  \frac{\partial C}
{\partial \omega_{31}^2} & 0\\
        \frac{\partial C}
{\partial \omega_{12}^2} &  \frac{\partial C}
{\partial \omega_{22}^2} &  \frac{\partial C}
{\partial \omega_{32}^2} & 0\\
        \frac{\partial C}
{\partial \omega_{13}^2} &  \frac{\partial C}
{\partial \omega_{23}^2} &  \frac{\partial C}
{\partial \omega_{33}^2} & 0\\
 \frac{\partial C}
{\partial \omega_{14}^2} &  \frac{\partial C}
{\partial \omega_{24}^2} &  \frac{\partial C}
{\partial \omega_{34}^2} & 0\\
        \frac{\partial C}
{\partial \beta_1^2} &  \frac{\partial C}
{\partial \beta_2^2} &  \frac{\partial C}
{\partial \beta_3^2} & 0\\
        \end{pmatrix}.
    \end{align}

The 4th Column being all zeros exists only due to the Bias Augment we did for the 2nd layer when we made an activation function that only = 1 or $a_4^2 = 1$. This would mean even if a weight was connected to that activation node (which there isn't) that specific weight would induce no change in the Cost since that activation node would always be constant and the derivative of a constant = 0